// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegolem

type LastBlock struct {
	ID    int64
	Block int64
}

type NumericAttribute struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Key       string
	Value     int64
}

type Payload struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Payload   []byte
}

type ProcessingStatus struct {
	Network                  string
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

type StringAttribute struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Key       string
	Value     string
}
