// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitegolem

type Annotation struct {
	EntityKey     string
	AnnotationKey string
	StringValue   *string
	NumericValue  *int64
}

type Entity struct {
	Key       string
	ExpiresAt int64
	Payload   []byte
}

type ProcessingStatus struct {
	Network                  string
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}
