-- name: InsertStringAttribute :exec
INSERT INTO STRING_ATTRIBUTES (
    ENTITY_KEY,
    FROM_BLOCK,
    TO_BLOCK,
    KEY,
    VALUE
) VALUES (?, ?, ?, ?, ?);

-- name: InsertNumericAttribute :exec
INSERT INTO NUMERIC_ATTRIBUTES (
    ENTITY_KEY,
    FROM_BLOCK,
    TO_BLOCK,
    KEY,
    VALUE
) VALUES (?, ?, ?, ?, ?);

-- name: InsertPayload :exec
INSERT INTO PAYLOADS (
    ENTITY_KEY,
    FROM_BLOCK,
    TO_BLOCK,
    PAYLOAD
) VALUES (?, ?, ?, ?);

-- name: DeleteStringAttributesBeforeBlock :exec
DELETE FROM STRING_ATTRIBUTES
WHERE FROM_BLOCK < ?;

-- name: DeleteNumericAttributesBeforeBlock :exec
DELETE FROM NUMERIC_ATTRIBUTES
WHERE FROM_BLOCK < ?;

-- name: DeletePayloadsBeforeBlock :exec
DELETE FROM PAYLOADS
WHERE FROM_BLOCK < ?;

-- name: UpsertLastBlock :exec
INSERT INTO LAST_BLOCK (ID, BLOCK)
VALUES (1, ?)
ON CONFLICT (ID) DO UPDATE SET BLOCK = excluded.BLOCK;

-- name: GetLastBlock :one
SELECT BLOCK FROM LAST_BLOCK;

-- name: TerminatePayloadAtBlock :exec
UPDATE PAYLOADS
SET TO_BLOCK = ?2
WHERE PAYLOADS.ENTITY_KEY = ?1 AND PAYLOADS.FROM_BLOCK <= ?2 AND PAYLOADS.TO_BLOCK > ?2;

-- name: TerminateStringAttributesAtBlock :exec
UPDATE STRING_ATTRIBUTES
SET TO_BLOCK = ?2
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ?1 AND STRING_ATTRIBUTES.FROM_BLOCK <= ?2 AND STRING_ATTRIBUTES.TO_BLOCK > ?2;

-- name: TerminateNumericAttributesAtBlock :exec
UPDATE NUMERIC_ATTRIBUTES
SET TO_BLOCK = ?2
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ?1 AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ?2 AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?2;

-- name: GetCreator :one
SELECT VALUE FROM STRING_ATTRIBUTES
WHERE ENTITY_KEY = ? AND KEY = '$creator' AND FROM_BLOCK <= ?
ORDER BY FROM_BLOCK DESC
LIMIT 1;

-- Helper queries for ChangeOwner operation
-- name: GetPayloadForEntityAtBlock :one
SELECT PAYLOADS.ENTITY_KEY, PAYLOADS.TO_BLOCK AS OLD_TO_BLOCK, PAYLOADS.PAYLOAD
FROM PAYLOADS
WHERE PAYLOADS.ENTITY_KEY = ? AND PAYLOADS.FROM_BLOCK <= ? AND PAYLOADS.TO_BLOCK > ?
LIMIT 1;

-- name: GetStringAttributesForEntityAtBlock :many
SELECT STRING_ATTRIBUTES.ENTITY_KEY, STRING_ATTRIBUTES.TO_BLOCK AS OLD_TO_BLOCK, STRING_ATTRIBUTES.KEY, STRING_ATTRIBUTES.VALUE
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?;

-- name: GetNumericAttributesForEntityAtBlock :many
SELECT NUMERIC_ATTRIBUTES.ENTITY_KEY, NUMERIC_ATTRIBUTES.TO_BLOCK AS OLD_TO_BLOCK, NUMERIC_ATTRIBUTES.KEY, NUMERIC_ATTRIBUTES.VALUE
FROM NUMERIC_ATTRIBUTES
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ? AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ? AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?;

-- Helper query to get active string attributes at a block
-- name: GetActiveStringAttributesAtBlock :many
SELECT STRING_ATTRIBUTES.KEY, STRING_ATTRIBUTES.VALUE
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?;

-- Helper queries for ChangeToBlock operation
-- name: GetPayloadForEntityAtBlockSimple :one
SELECT PAYLOADS.ENTITY_KEY, PAYLOADS.PAYLOAD
FROM PAYLOADS
WHERE PAYLOADS.ENTITY_KEY = ? AND PAYLOADS.FROM_BLOCK <= ? AND PAYLOADS.TO_BLOCK > ?
LIMIT 1;

-- name: GetStringAttributesForEntityAtBlockSimple :many
SELECT STRING_ATTRIBUTES.ENTITY_KEY, STRING_ATTRIBUTES.KEY, STRING_ATTRIBUTES.VALUE
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?;

-- name: GetNumericAttributesForEntityAtBlockSimple :many
SELECT NUMERIC_ATTRIBUTES.ENTITY_KEY, NUMERIC_ATTRIBUTES.KEY, NUMERIC_ATTRIBUTES.VALUE
FROM NUMERIC_ATTRIBUTES
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ? AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ? AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?;

-- Processing status queries (kept for network tracking)
-- name: GetProcessingStatus :one
SELECT last_processed_block_number, last_processed_block_hash FROM processing_status WHERE network = ?;

-- name: UpdateProcessingStatus :exec
UPDATE processing_status SET last_processed_block_number = ?, last_processed_block_hash = ? WHERE network = ?;

-- name: InsertProcessingStatus :exec
INSERT INTO processing_status (network, last_processed_block_number, last_processed_block_hash) VALUES (?, ?, ?);

-- name: HasProcessingStatus :one
SELECT COUNT(*) > 0 FROM processing_status WHERE network = ?;

-- name: CountNetworks :one
SELECT COUNT(DISTINCT network) FROM processing_status;

-- name: DeleteProcessingStatus :exec
DELETE FROM processing_status WHERE network = ?;

-- Query operations for reading entities (adapted for temporal schema)
-- name: GetStringAnnotations :many
SELECT STRING_ATTRIBUTES.KEY AS annotation_key, STRING_ATTRIBUTES.VALUE AS value
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?;

-- name: GetNumericAnnotations :many
SELECT NUMERIC_ATTRIBUTES.KEY AS annotation_key, NUMERIC_ATTRIBUTES.VALUE AS value
FROM NUMERIC_ATTRIBUTES
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ? AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ? AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?;

-- name: GetEntityCount :one
SELECT COUNT(DISTINCT ENTITY_KEY)
FROM PAYLOADS
WHERE FROM_BLOCK <= ? AND TO_BLOCK > ?;

-- name: GetGarbageCount :one
SELECT
(
  SELECT COUNT(1)
  FROM PAYLOADS
  WHERE PAYLOADS.TO_BLOCK <= ?
)
+
(
  SELECT COUNT(1)
  FROM STRING_ATTRIBUTES
  WHERE STRING_ATTRIBUTES.TO_BLOCK <= ?
)
+
(
  SELECT COUNT(1)
  FROM NUMERIC_ATTRIBUTES
  WHERE NUMERIC_ATTRIBUTES.TO_BLOCK <= ?
);

-- name: GetLastProcessedBlockNumber :one
SELECT last_processed_block_number
FROM processing_status
LIMIT 1;
