// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlitegolem

import (
	"context"
)

const countNetworks = `-- name: CountNetworks :one
SELECT COUNT(DISTINCT network) FROM processing_status
`

func (q *Queries) CountNetworks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNumericAttributesBeforeBlock = `-- name: DeleteNumericAttributesBeforeBlock :exec
DELETE FROM NUMERIC_ATTRIBUTES
WHERE FROM_BLOCK < ?
`

func (q *Queries) DeleteNumericAttributesBeforeBlock(ctx context.Context, fromBlock int64) error {
	_, err := q.db.ExecContext(ctx, deleteNumericAttributesBeforeBlock, fromBlock)
	return err
}

const deletePayloadsBeforeBlock = `-- name: DeletePayloadsBeforeBlock :exec
DELETE FROM PAYLOADS
WHERE FROM_BLOCK < ?
`

func (q *Queries) DeletePayloadsBeforeBlock(ctx context.Context, fromBlock int64) error {
	_, err := q.db.ExecContext(ctx, deletePayloadsBeforeBlock, fromBlock)
	return err
}

const deleteProcessingStatus = `-- name: DeleteProcessingStatus :exec
DELETE FROM processing_status WHERE network = ?
`

func (q *Queries) DeleteProcessingStatus(ctx context.Context, network string) error {
	_, err := q.db.ExecContext(ctx, deleteProcessingStatus, network)
	return err
}

const deleteStringAttributesBeforeBlock = `-- name: DeleteStringAttributesBeforeBlock :exec
DELETE FROM STRING_ATTRIBUTES
WHERE FROM_BLOCK < ?
`

func (q *Queries) DeleteStringAttributesBeforeBlock(ctx context.Context, fromBlock int64) error {
	_, err := q.db.ExecContext(ctx, deleteStringAttributesBeforeBlock, fromBlock)
	return err
}

const getActiveStringAttributesAtBlock = `-- name: GetActiveStringAttributesAtBlock :many
SELECT STRING_ATTRIBUTES.KEY, STRING_ATTRIBUTES.VALUE
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?
`

type GetActiveStringAttributesAtBlockParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetActiveStringAttributesAtBlockRow struct {
	Key   string
	Value string
}

// Helper query to get active string attributes at a block
func (q *Queries) GetActiveStringAttributesAtBlock(ctx context.Context, arg GetActiveStringAttributesAtBlockParams) ([]GetActiveStringAttributesAtBlockRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveStringAttributesAtBlock, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveStringAttributesAtBlockRow
	for rows.Next() {
		var i GetActiveStringAttributesAtBlockRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreator = `-- name: GetCreator :one
SELECT VALUE FROM STRING_ATTRIBUTES
WHERE ENTITY_KEY = ? AND KEY = '$creator' AND FROM_BLOCK <= ?
ORDER BY FROM_BLOCK DESC
LIMIT 1
`

type GetCreatorParams struct {
	EntityKey []byte
	FromBlock int64
}

func (q *Queries) GetCreator(ctx context.Context, arg GetCreatorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCreator, arg.EntityKey, arg.FromBlock)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getEntityCount = `-- name: GetEntityCount :one
SELECT COUNT(DISTINCT ENTITY_KEY)
FROM PAYLOADS
WHERE FROM_BLOCK <= ? AND TO_BLOCK > ?
`

type GetEntityCountParams struct {
	FromBlock int64
	ToBlock   int64
}

func (q *Queries) GetEntityCount(ctx context.Context, arg GetEntityCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEntityCount, arg.FromBlock, arg.ToBlock)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGarbageCount = `-- name: GetGarbageCount :one
SELECT
(
  SELECT COUNT(1)
  FROM PAYLOADS
  WHERE PAYLOADS.TO_BLOCK <= ?
)
+
(
  SELECT COUNT(1)
  FROM STRING_ATTRIBUTES
  WHERE STRING_ATTRIBUTES.TO_BLOCK <= ?
)
+
(
  SELECT COUNT(1)
  FROM NUMERIC_ATTRIBUTES
  WHERE NUMERIC_ATTRIBUTES.TO_BLOCK <= ?
)
`

type GetGarbageCountParams struct {
	ToBlock   int64
	ToBlock_2 int64
	ToBlock_3 int64
}

func (q *Queries) GetGarbageCount(ctx context.Context, arg GetGarbageCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGarbageCount, arg.ToBlock, arg.ToBlock_2, arg.ToBlock_3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLastBlock = `-- name: GetLastBlock :one
SELECT BLOCK FROM LAST_BLOCK
`

func (q *Queries) GetLastBlock(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastBlock)
	var block int64
	err := row.Scan(&block)
	return block, err
}

const getLastProcessedBlockNumber = `-- name: GetLastProcessedBlockNumber :one
SELECT last_processed_block_number
FROM processing_status
LIMIT 1
`

func (q *Queries) GetLastProcessedBlockNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastProcessedBlockNumber)
	var last_processed_block_number int64
	err := row.Scan(&last_processed_block_number)
	return last_processed_block_number, err
}

const getNumericAnnotations = `-- name: GetNumericAnnotations :many
SELECT NUMERIC_ATTRIBUTES.KEY AS annotation_key, NUMERIC_ATTRIBUTES.VALUE AS value
FROM NUMERIC_ATTRIBUTES
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ? AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ? AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?
`

type GetNumericAnnotationsParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetNumericAnnotationsRow struct {
	AnnotationKey string
	Value         int64
}

func (q *Queries) GetNumericAnnotations(ctx context.Context, arg GetNumericAnnotationsParams) ([]GetNumericAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNumericAnnotations, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNumericAnnotationsRow
	for rows.Next() {
		var i GetNumericAnnotationsRow
		if err := rows.Scan(&i.AnnotationKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNumericAttributesForEntityAtBlock = `-- name: GetNumericAttributesForEntityAtBlock :many
SELECT NUMERIC_ATTRIBUTES.ENTITY_KEY, NUMERIC_ATTRIBUTES.TO_BLOCK AS OLD_TO_BLOCK, NUMERIC_ATTRIBUTES.KEY, NUMERIC_ATTRIBUTES.VALUE
FROM NUMERIC_ATTRIBUTES
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ? AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ? AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?
`

type GetNumericAttributesForEntityAtBlockParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetNumericAttributesForEntityAtBlockRow struct {
	EntityKey  []byte
	OldToBlock int64
	Key        string
	Value      int64
}

func (q *Queries) GetNumericAttributesForEntityAtBlock(ctx context.Context, arg GetNumericAttributesForEntityAtBlockParams) ([]GetNumericAttributesForEntityAtBlockRow, error) {
	rows, err := q.db.QueryContext(ctx, getNumericAttributesForEntityAtBlock, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNumericAttributesForEntityAtBlockRow
	for rows.Next() {
		var i GetNumericAttributesForEntityAtBlockRow
		if err := rows.Scan(
			&i.EntityKey,
			&i.OldToBlock,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNumericAttributesForEntityAtBlockSimple = `-- name: GetNumericAttributesForEntityAtBlockSimple :many
SELECT NUMERIC_ATTRIBUTES.ENTITY_KEY, NUMERIC_ATTRIBUTES.KEY, NUMERIC_ATTRIBUTES.VALUE
FROM NUMERIC_ATTRIBUTES
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ? AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ? AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?
`

type GetNumericAttributesForEntityAtBlockSimpleParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetNumericAttributesForEntityAtBlockSimpleRow struct {
	EntityKey []byte
	Key       string
	Value     int64
}

func (q *Queries) GetNumericAttributesForEntityAtBlockSimple(ctx context.Context, arg GetNumericAttributesForEntityAtBlockSimpleParams) ([]GetNumericAttributesForEntityAtBlockSimpleRow, error) {
	rows, err := q.db.QueryContext(ctx, getNumericAttributesForEntityAtBlockSimple, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNumericAttributesForEntityAtBlockSimpleRow
	for rows.Next() {
		var i GetNumericAttributesForEntityAtBlockSimpleRow
		if err := rows.Scan(&i.EntityKey, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayloadForEntityAtBlock = `-- name: GetPayloadForEntityAtBlock :one
SELECT PAYLOADS.ENTITY_KEY, PAYLOADS.TO_BLOCK AS OLD_TO_BLOCK, PAYLOADS.PAYLOAD
FROM PAYLOADS
WHERE PAYLOADS.ENTITY_KEY = ? AND PAYLOADS.FROM_BLOCK <= ? AND PAYLOADS.TO_BLOCK > ?
LIMIT 1
`

type GetPayloadForEntityAtBlockParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetPayloadForEntityAtBlockRow struct {
	EntityKey  []byte
	OldToBlock int64
	Payload    []byte
}

// Helper queries for ChangeOwner operation
func (q *Queries) GetPayloadForEntityAtBlock(ctx context.Context, arg GetPayloadForEntityAtBlockParams) (GetPayloadForEntityAtBlockRow, error) {
	row := q.db.QueryRowContext(ctx, getPayloadForEntityAtBlock, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	var i GetPayloadForEntityAtBlockRow
	err := row.Scan(&i.EntityKey, &i.OldToBlock, &i.Payload)
	return i, err
}

const getPayloadForEntityAtBlockSimple = `-- name: GetPayloadForEntityAtBlockSimple :one
SELECT PAYLOADS.ENTITY_KEY, PAYLOADS.PAYLOAD
FROM PAYLOADS
WHERE PAYLOADS.ENTITY_KEY = ? AND PAYLOADS.FROM_BLOCK <= ? AND PAYLOADS.TO_BLOCK > ?
LIMIT 1
`

type GetPayloadForEntityAtBlockSimpleParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetPayloadForEntityAtBlockSimpleRow struct {
	EntityKey []byte
	Payload   []byte
}

// Helper queries for ChangeToBlock operation
func (q *Queries) GetPayloadForEntityAtBlockSimple(ctx context.Context, arg GetPayloadForEntityAtBlockSimpleParams) (GetPayloadForEntityAtBlockSimpleRow, error) {
	row := q.db.QueryRowContext(ctx, getPayloadForEntityAtBlockSimple, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	var i GetPayloadForEntityAtBlockSimpleRow
	err := row.Scan(&i.EntityKey, &i.Payload)
	return i, err
}

const getProcessingStatus = `-- name: GetProcessingStatus :one
SELECT last_processed_block_number, last_processed_block_hash FROM processing_status WHERE network = ?
`

type GetProcessingStatusRow struct {
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

// Processing status queries (kept for network tracking)
func (q *Queries) GetProcessingStatus(ctx context.Context, network string) (GetProcessingStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getProcessingStatus, network)
	var i GetProcessingStatusRow
	err := row.Scan(&i.LastProcessedBlockNumber, &i.LastProcessedBlockHash)
	return i, err
}

const getStringAnnotations = `-- name: GetStringAnnotations :many
SELECT STRING_ATTRIBUTES.KEY AS annotation_key, STRING_ATTRIBUTES.VALUE AS value
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?
`

type GetStringAnnotationsParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetStringAnnotationsRow struct {
	AnnotationKey string
	Value         string
}

// Query operations for reading entities (adapted for temporal schema)
func (q *Queries) GetStringAnnotations(ctx context.Context, arg GetStringAnnotationsParams) ([]GetStringAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStringAnnotations, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStringAnnotationsRow
	for rows.Next() {
		var i GetStringAnnotationsRow
		if err := rows.Scan(&i.AnnotationKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStringAttributesForEntityAtBlock = `-- name: GetStringAttributesForEntityAtBlock :many
SELECT STRING_ATTRIBUTES.ENTITY_KEY, STRING_ATTRIBUTES.TO_BLOCK AS OLD_TO_BLOCK, STRING_ATTRIBUTES.KEY, STRING_ATTRIBUTES.VALUE
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?
`

type GetStringAttributesForEntityAtBlockParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetStringAttributesForEntityAtBlockRow struct {
	EntityKey  []byte
	OldToBlock int64
	Key        string
	Value      string
}

func (q *Queries) GetStringAttributesForEntityAtBlock(ctx context.Context, arg GetStringAttributesForEntityAtBlockParams) ([]GetStringAttributesForEntityAtBlockRow, error) {
	rows, err := q.db.QueryContext(ctx, getStringAttributesForEntityAtBlock, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStringAttributesForEntityAtBlockRow
	for rows.Next() {
		var i GetStringAttributesForEntityAtBlockRow
		if err := rows.Scan(
			&i.EntityKey,
			&i.OldToBlock,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStringAttributesForEntityAtBlockSimple = `-- name: GetStringAttributesForEntityAtBlockSimple :many
SELECT STRING_ATTRIBUTES.ENTITY_KEY, STRING_ATTRIBUTES.KEY, STRING_ATTRIBUTES.VALUE
FROM STRING_ATTRIBUTES
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ? AND STRING_ATTRIBUTES.FROM_BLOCK <= ? AND STRING_ATTRIBUTES.TO_BLOCK > ?
`

type GetStringAttributesForEntityAtBlockSimpleParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
}

type GetStringAttributesForEntityAtBlockSimpleRow struct {
	EntityKey []byte
	Key       string
	Value     string
}

func (q *Queries) GetStringAttributesForEntityAtBlockSimple(ctx context.Context, arg GetStringAttributesForEntityAtBlockSimpleParams) ([]GetStringAttributesForEntityAtBlockSimpleRow, error) {
	rows, err := q.db.QueryContext(ctx, getStringAttributesForEntityAtBlockSimple, arg.EntityKey, arg.FromBlock, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStringAttributesForEntityAtBlockSimpleRow
	for rows.Next() {
		var i GetStringAttributesForEntityAtBlockSimpleRow
		if err := rows.Scan(&i.EntityKey, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasProcessingStatus = `-- name: HasProcessingStatus :one
SELECT COUNT(*) > 0 FROM processing_status WHERE network = ?
`

func (q *Queries) HasProcessingStatus(ctx context.Context, network string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasProcessingStatus, network)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNumericAttribute = `-- name: InsertNumericAttribute :exec
INSERT INTO NUMERIC_ATTRIBUTES (
    ENTITY_KEY,
    FROM_BLOCK,
    TO_BLOCK,
    KEY,
    VALUE
) VALUES (?, ?, ?, ?, ?)
`

type InsertNumericAttributeParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Key       string
	Value     int64
}

func (q *Queries) InsertNumericAttribute(ctx context.Context, arg InsertNumericAttributeParams) error {
	_, err := q.db.ExecContext(ctx, insertNumericAttribute,
		arg.EntityKey,
		arg.FromBlock,
		arg.ToBlock,
		arg.Key,
		arg.Value,
	)
	return err
}

const insertPayload = `-- name: InsertPayload :exec
INSERT INTO PAYLOADS (
    ENTITY_KEY,
    FROM_BLOCK,
    TO_BLOCK,
    PAYLOAD
) VALUES (?, ?, ?, ?)
`

type InsertPayloadParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Payload   []byte
}

func (q *Queries) InsertPayload(ctx context.Context, arg InsertPayloadParams) error {
	_, err := q.db.ExecContext(ctx, insertPayload,
		arg.EntityKey,
		arg.FromBlock,
		arg.ToBlock,
		arg.Payload,
	)
	return err
}

const insertProcessingStatus = `-- name: InsertProcessingStatus :exec
INSERT INTO processing_status (network, last_processed_block_number, last_processed_block_hash) VALUES (?, ?, ?)
`

type InsertProcessingStatusParams struct {
	Network                  string
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
}

func (q *Queries) InsertProcessingStatus(ctx context.Context, arg InsertProcessingStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertProcessingStatus, arg.Network, arg.LastProcessedBlockNumber, arg.LastProcessedBlockHash)
	return err
}

const insertStringAttribute = `-- name: InsertStringAttribute :exec
INSERT INTO STRING_ATTRIBUTES (
    ENTITY_KEY,
    FROM_BLOCK,
    TO_BLOCK,
    KEY,
    VALUE
) VALUES (?, ?, ?, ?, ?)
`

type InsertStringAttributeParams struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Key       string
	Value     string
}

func (q *Queries) InsertStringAttribute(ctx context.Context, arg InsertStringAttributeParams) error {
	_, err := q.db.ExecContext(ctx, insertStringAttribute,
		arg.EntityKey,
		arg.FromBlock,
		arg.ToBlock,
		arg.Key,
		arg.Value,
	)
	return err
}

const terminateNumericAttributesAtBlock = `-- name: TerminateNumericAttributesAtBlock :exec
UPDATE NUMERIC_ATTRIBUTES
SET TO_BLOCK = ?2
WHERE NUMERIC_ATTRIBUTES.ENTITY_KEY = ?1 AND NUMERIC_ATTRIBUTES.FROM_BLOCK <= ?2 AND NUMERIC_ATTRIBUTES.TO_BLOCK > ?2
`

type TerminateNumericAttributesAtBlockParams struct {
	EntityKey []byte
	ToBlock   int64
}

func (q *Queries) TerminateNumericAttributesAtBlock(ctx context.Context, arg TerminateNumericAttributesAtBlockParams) error {
	_, err := q.db.ExecContext(ctx, terminateNumericAttributesAtBlock, arg.EntityKey, arg.ToBlock)
	return err
}

const terminatePayloadAtBlock = `-- name: TerminatePayloadAtBlock :exec
UPDATE PAYLOADS
SET TO_BLOCK = ?2
WHERE PAYLOADS.ENTITY_KEY = ?1 AND PAYLOADS.FROM_BLOCK <= ?2 AND PAYLOADS.TO_BLOCK > ?2
`

type TerminatePayloadAtBlockParams struct {
	EntityKey []byte
	ToBlock   int64
}

func (q *Queries) TerminatePayloadAtBlock(ctx context.Context, arg TerminatePayloadAtBlockParams) error {
	_, err := q.db.ExecContext(ctx, terminatePayloadAtBlock, arg.EntityKey, arg.ToBlock)
	return err
}

const terminateStringAttributesAtBlock = `-- name: TerminateStringAttributesAtBlock :exec
UPDATE STRING_ATTRIBUTES
SET TO_BLOCK = ?2
WHERE STRING_ATTRIBUTES.ENTITY_KEY = ?1 AND STRING_ATTRIBUTES.FROM_BLOCK <= ?2 AND STRING_ATTRIBUTES.TO_BLOCK > ?2
`

type TerminateStringAttributesAtBlockParams struct {
	EntityKey []byte
	ToBlock   int64
}

func (q *Queries) TerminateStringAttributesAtBlock(ctx context.Context, arg TerminateStringAttributesAtBlockParams) error {
	_, err := q.db.ExecContext(ctx, terminateStringAttributesAtBlock, arg.EntityKey, arg.ToBlock)
	return err
}

const updateProcessingStatus = `-- name: UpdateProcessingStatus :exec
UPDATE processing_status SET last_processed_block_number = ?, last_processed_block_hash = ? WHERE network = ?
`

type UpdateProcessingStatusParams struct {
	LastProcessedBlockNumber int64
	LastProcessedBlockHash   string
	Network                  string
}

func (q *Queries) UpdateProcessingStatus(ctx context.Context, arg UpdateProcessingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessingStatus, arg.LastProcessedBlockNumber, arg.LastProcessedBlockHash, arg.Network)
	return err
}

const upsertLastBlock = `-- name: UpsertLastBlock :exec
INSERT INTO LAST_BLOCK (ID, BLOCK)
VALUES (1, ?)
ON CONFLICT (ID) DO UPDATE SET BLOCK = excluded.BLOCK
`

func (q *Queries) UpsertLastBlock(ctx context.Context, block int64) error {
	_, err := q.db.ExecContext(ctx, upsertLastBlock, block)
	return err
}
