CREATE TABLE IF NOT EXISTS STRING_ATTRIBUTES (
    ENTITY_KEY BLOB NOT NULL,
    FROM_BLOCK INTEGER NOT NULL,
    TO_BLOCK INTEGER NOT NULL,
    KEY TEXT NOT NULL,
    VALUE TEXT NOT NULL,
    PRIMARY KEY (ENTITY_KEY, KEY, FROM_BLOCK)
);

CREATE TABLE IF NOT EXISTS NUMERIC_ATTRIBUTES (
    ENTITY_KEY BLOB NOT NULL,
    FROM_BLOCK INTEGER NOT NULL,
    TO_BLOCK INTEGER NOT NULL,
    KEY TEXT NOT NULL,
    VALUE INTEGER NOT NULL,
    PRIMARY KEY (ENTITY_KEY, KEY, FROM_BLOCK)
);

CREATE TABLE IF NOT EXISTS PAYLOADS (
    ENTITY_KEY BLOB NOT NULL,
    FROM_BLOCK INTEGER NOT NULL,
    TO_BLOCK INTEGER NOT NULL,
    PAYLOAD BLOB NOT NULL,
    PRIMARY KEY (ENTITY_KEY, FROM_BLOCK)
);

CREATE TABLE IF NOT EXISTS LAST_BLOCK (
    ID INTEGER NOT NULL DEFAULT 1 CHECK (ID = 1),
    BLOCK INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

INSERT OR IGNORE INTO LAST_BLOCK (ID, BLOCK)
VALUES (1, 0);

CREATE TABLE IF NOT EXISTS schema_versions (
    id INTEGER NOT NULL PRIMARY KEY,
    entities INTEGER
);

CREATE TABLE IF NOT EXISTS processing_status (
    network TEXT NOT NULL PRIMARY KEY,
    last_processed_block_number INTEGER NOT NULL,
    last_processed_block_hash TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS STRING_ATTRIBUTES_ENTITY_KEY_VALUE_INDEX ON STRING_ATTRIBUTES (FROM_BLOCK, TO_BLOCK, KEY, VALUE);
CREATE INDEX IF NOT EXISTS STRING_ATTRIBUTES_ENTITY_KEY_INDEX ON STRING_ATTRIBUTES (FROM_BLOCK, TO_BLOCK, KEY);
CREATE INDEX IF NOT EXISTS STRING_ATTRIBUTES_DELETE_INDEX ON STRING_ATTRIBUTES (TO_BLOCK);
CREATE INDEX IF NOT EXISTS NUMERIC_ATTRIBUTES_ENTITY_KEY_VALUE_INDEX ON NUMERIC_ATTRIBUTES (FROM_BLOCK, TO_BLOCK, KEY, VALUE);
CREATE INDEX IF NOT EXISTS NUMERIC_ATTRIBUTES_ENTITY_KEY_INDEX ON NUMERIC_ATTRIBUTES (FROM_BLOCK, TO_BLOCK, KEY);
CREATE INDEX IF NOT EXISTS NUMERIC_ATTRIBUTES_DELETE_INDEX ON NUMERIC_ATTRIBUTES (TO_BLOCK);
CREATE INDEX IF NOT EXISTS PAYLOADS_ENTITY_KEY_INDEX ON PAYLOADS (ENTITY_KEY, FROM_BLOCK, TO_BLOCK);
CREATE INDEX IF NOT EXISTS PAYLOADS_DELETE_INDEX ON PAYLOADS (TO_BLOCK);
