// Code generated by rlpgen. DO NOT EDIT.

package storageutil

import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *KeyList) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	_tmp1 := w.List()
	for _, _tmp2 := range obj.Keys {
		w.WriteBytes(_tmp2[:])
	}
	w.ListEnd(_tmp1)
	w.ListEnd(_tmp0)
	return w.Flush()
}
