// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

type Entity struct {
	Key       string
	ExpiresAt int64
	Payload   []byte
}

type NumericAnnotation struct {
	EntityKey     string
	AnnotationKey string
	Value         int64
}

type StringAnnotation struct {
	EntityKey     string
	AnnotationKey string
	Value         string
}
