// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: storagetx/storage_transaction.proto

package storagetx

import (
	entity "github.com/ethereum/go-ethereum/golem-base/storageutil/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StorageTransaction represents a transaction that can be applied to the storage layer.
// It contains a list of Create operations, a list of Update operations and a list of Delete operations.
//
// Semantics of the transaction operations are as follows:
//   - Create: adds new entities to the storage layer. Each entity has a BTL (number of blocks), a payload and a list of annotations. The Key of the entity is derived from the payload content, the transaction hash where the entity was created and the index of the create operation in the transaction.
//   - Update: updates existing entities. Each entity has a key, a BTL (number of blocks), a payload and a list of annotations. If the entity does not exist, the operation fails, failing the whole transaction.
//   - Delete: removes entities from the storage layer. If the entity does not exist, the operation fails, failing back the whole transaction.
//   - ExtendBTL: extends the life of some entity by the specified BTL (number of blocks).
//
// The transaction is atomic, meaning that all operations are applied or none are.
//
// Annotations are key-value pairs where the key is a string and the value is either a string or a number.
// The key-value pairs are used to build indexes and to query the storage layer.
// Same key can have both string and numeric annotation, but not multiple values of the same type.
type StorageTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Create []*Create    `protobuf:"bytes,1,rep,name=create,proto3" json:"create,omitempty"`
	Update []*Update    `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty"`
	Delete []*Delete    `protobuf:"bytes,3,rep,name=delete,proto3" json:"delete,omitempty"`
	Extend []*ExtendBTL `protobuf:"bytes,4,rep,name=extend,proto3" json:"extend,omitempty"`
}

func (x *StorageTransaction) Reset() {
	*x = StorageTransaction{}
	mi := &file_storagetx_storage_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageTransaction) ProtoMessage() {}

func (x *StorageTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_storagetx_storage_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageTransaction.ProtoReflect.Descriptor instead.
func (*StorageTransaction) Descriptor() ([]byte, []int) {
	return file_storagetx_storage_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *StorageTransaction) GetCreate() []*Create {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *StorageTransaction) GetUpdate() []*Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *StorageTransaction) GetDelete() []*Delete {
	if x != nil {
		return x.Delete
	}
	return nil
}

func (x *StorageTransaction) GetExtend() []*ExtendBTL {
	if x != nil {
		return x.Extend
	}
	return nil
}

type Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BTL                uint64                      `protobuf:"varint,1,opt,name=BTL,proto3" json:"BTL,omitempty"`
	Payload            []byte                      `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	StringAnnotations  []*entity.StringAnnotation  `protobuf:"bytes,3,rep,name=string_annotations,json=stringAnnotations,proto3" json:"string_annotations,omitempty"`
	NumericAnnotations []*entity.NumericAnnotation `protobuf:"bytes,4,rep,name=numeric_annotations,json=numericAnnotations,proto3" json:"numeric_annotations,omitempty"`
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_storagetx_storage_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_storagetx_storage_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_storagetx_storage_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Create) GetBTL() uint64 {
	if x != nil {
		return x.BTL
	}
	return 0
}

func (x *Create) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Create) GetStringAnnotations() []*entity.StringAnnotation {
	if x != nil {
		return x.StringAnnotations
	}
	return nil
}

func (x *Create) GetNumericAnnotations() []*entity.NumericAnnotation {
	if x != nil {
		return x.NumericAnnotations
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityKey          []byte                      `protobuf:"bytes,1,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	BTL                uint64                      `protobuf:"varint,2,opt,name=BTL,proto3" json:"BTL,omitempty"`
	Payload            []byte                      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	StringAnnotations  []*entity.StringAnnotation  `protobuf:"bytes,4,rep,name=string_annotations,json=stringAnnotations,proto3" json:"string_annotations,omitempty"`
	NumericAnnotations []*entity.NumericAnnotation `protobuf:"bytes,5,rep,name=numeric_annotations,json=numericAnnotations,proto3" json:"numeric_annotations,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_storagetx_storage_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_storagetx_storage_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_storagetx_storage_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Update) GetEntityKey() []byte {
	if x != nil {
		return x.EntityKey
	}
	return nil
}

func (x *Update) GetBTL() uint64 {
	if x != nil {
		return x.BTL
	}
	return 0
}

func (x *Update) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Update) GetStringAnnotations() []*entity.StringAnnotation {
	if x != nil {
		return x.StringAnnotations
	}
	return nil
}

func (x *Update) GetNumericAnnotations() []*entity.NumericAnnotation {
	if x != nil {
		return x.NumericAnnotations
	}
	return nil
}

type ExtendBTL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityKey      []byte `protobuf:"bytes,1,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	NumberOfBlocks uint64 `protobuf:"varint,2,opt,name=number_of_blocks,json=numberOfBlocks,proto3" json:"number_of_blocks,omitempty"`
}

func (x *ExtendBTL) Reset() {
	*x = ExtendBTL{}
	mi := &file_storagetx_storage_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendBTL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendBTL) ProtoMessage() {}

func (x *ExtendBTL) ProtoReflect() protoreflect.Message {
	mi := &file_storagetx_storage_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendBTL.ProtoReflect.Descriptor instead.
func (*ExtendBTL) Descriptor() ([]byte, []int) {
	return file_storagetx_storage_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ExtendBTL) GetEntityKey() []byte {
	if x != nil {
		return x.EntityKey
	}
	return nil
}

func (x *ExtendBTL) GetNumberOfBlocks() uint64 {
	if x != nil {
		return x.NumberOfBlocks
	}
	return 0
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityKey []byte `protobuf:"bytes,1,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_storagetx_storage_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_storagetx_storage_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_storagetx_storage_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *Delete) GetEntityKey() []byte {
	if x != nil {
		return x.EntityKey
	}
	return nil
}

var File_storagetx_storage_transaction_proto protoreflect.FileDescriptor

var file_storagetx_storage_transaction_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x74, 0x78, 0x2f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x74, 0x78,
	0x1a, 0x27, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x01, 0x0a, 0x12, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x74, 0x78, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x74, 0x78, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x74, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x74, 0x78, 0x2e, 0x45, 0x78,
	0x74, 0x65, 0x6e, 0x64, 0x42, 0x54, 0x4c, 0x52, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x22,
	0xc9, 0x01, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x54,
	0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x42, 0x54, 0x4c, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x47, 0x0a, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x4a, 0x0a, 0x13, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x41, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63,
	0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xe8, 0x01, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x54, 0x4c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x42, 0x54, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x47, 0x0a, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4a, 0x0a, 0x13, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x12, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x41, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x54, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x42, 0x54, 0x4c, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x27, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4b, 0x65, 0x79, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x67, 0x6f, 0x2d,
	0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x67, 0x6f, 0x6c, 0x65, 0x6d, 0x2d, 0x62,
	0x61, 0x73, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x74, 0x78, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storagetx_storage_transaction_proto_rawDescOnce sync.Once
	file_storagetx_storage_transaction_proto_rawDescData = file_storagetx_storage_transaction_proto_rawDesc
)

func file_storagetx_storage_transaction_proto_rawDescGZIP() []byte {
	file_storagetx_storage_transaction_proto_rawDescOnce.Do(func() {
		file_storagetx_storage_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_storagetx_storage_transaction_proto_rawDescData)
	})
	return file_storagetx_storage_transaction_proto_rawDescData
}

var file_storagetx_storage_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_storagetx_storage_transaction_proto_goTypes = []any{
	(*StorageTransaction)(nil),       // 0: storagetx.StorageTransaction
	(*Create)(nil),                   // 1: storagetx.Create
	(*Update)(nil),                   // 2: storagetx.Update
	(*ExtendBTL)(nil),                // 3: storagetx.ExtendBTL
	(*Delete)(nil),                   // 4: storagetx.Delete
	(*entity.StringAnnotation)(nil),  // 5: entity.StringAnnotation
	(*entity.NumericAnnotation)(nil), // 6: entity.NumericAnnotation
}
var file_storagetx_storage_transaction_proto_depIdxs = []int32{
	1, // 0: storagetx.StorageTransaction.create:type_name -> storagetx.Create
	2, // 1: storagetx.StorageTransaction.update:type_name -> storagetx.Update
	4, // 2: storagetx.StorageTransaction.delete:type_name -> storagetx.Delete
	3, // 3: storagetx.StorageTransaction.extend:type_name -> storagetx.ExtendBTL
	5, // 4: storagetx.Create.string_annotations:type_name -> entity.StringAnnotation
	6, // 5: storagetx.Create.numeric_annotations:type_name -> entity.NumericAnnotation
	5, // 6: storagetx.Update.string_annotations:type_name -> entity.StringAnnotation
	6, // 7: storagetx.Update.numeric_annotations:type_name -> entity.NumericAnnotation
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_storagetx_storage_transaction_proto_init() }
func file_storagetx_storage_transaction_proto_init() {
	if File_storagetx_storage_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storagetx_storage_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storagetx_storage_transaction_proto_goTypes,
		DependencyIndexes: file_storagetx_storage_transaction_proto_depIdxs,
		MessageInfos:      file_storagetx_storage_transaction_proto_msgTypes,
	}.Build()
	File_storagetx_storage_transaction_proto = out.File
	file_storagetx_storage_transaction_proto_rawDesc = nil
	file_storagetx_storage_transaction_proto_goTypes = nil
	file_storagetx_storage_transaction_proto_depIdxs = nil
}
