// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: storageutil/entity/active_payload.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntityMetaData represents information about an entity that is currently active in the storage layer.
// This is what stored in the state.
// It contains a BTL (number of blocks) and a list of annotations.
// The Key of the entity is derived from the payload content and the transaction hash where the entity was created.
type EntityMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpiresAtBlock     uint64               `protobuf:"varint,1,opt,name=expires_at_block,json=expiresAtBlock,proto3" json:"expires_at_block,omitempty"`
	StringAnnotations  []*StringAnnotation  `protobuf:"bytes,2,rep,name=string_annotations,json=stringAnnotations,proto3" json:"string_annotations,omitempty"`
	NumericAnnotations []*NumericAnnotation `protobuf:"bytes,3,rep,name=numeric_annotations,json=numericAnnotations,proto3" json:"numeric_annotations,omitempty"`
	Owner              []byte               `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *EntityMetaData) Reset() {
	*x = EntityMetaData{}
	mi := &file_storageutil_entity_active_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMetaData) ProtoMessage() {}

func (x *EntityMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_storageutil_entity_active_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMetaData.ProtoReflect.Descriptor instead.
func (*EntityMetaData) Descriptor() ([]byte, []int) {
	return file_storageutil_entity_active_payload_proto_rawDescGZIP(), []int{0}
}

func (x *EntityMetaData) GetExpiresAtBlock() uint64 {
	if x != nil {
		return x.ExpiresAtBlock
	}
	return 0
}

func (x *EntityMetaData) GetStringAnnotations() []*StringAnnotation {
	if x != nil {
		return x.StringAnnotations
	}
	return nil
}

func (x *EntityMetaData) GetNumericAnnotations() []*NumericAnnotation {
	if x != nil {
		return x.NumericAnnotations
	}
	return nil
}

func (x *EntityMetaData) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

type StringAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringAnnotation) Reset() {
	*x = StringAnnotation{}
	mi := &file_storageutil_entity_active_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringAnnotation) ProtoMessage() {}

func (x *StringAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_storageutil_entity_active_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringAnnotation.ProtoReflect.Descriptor instead.
func (*StringAnnotation) Descriptor() ([]byte, []int) {
	return file_storageutil_entity_active_payload_proto_rawDescGZIP(), []int{1}
}

func (x *StringAnnotation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StringAnnotation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NumericAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value uint64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NumericAnnotation) Reset() {
	*x = NumericAnnotation{}
	mi := &file_storageutil_entity_active_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericAnnotation) ProtoMessage() {}

func (x *NumericAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_storageutil_entity_active_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericAnnotation.ProtoReflect.Descriptor instead.
func (*NumericAnnotation) Descriptor() ([]byte, []int) {
	return file_storageutil_entity_active_payload_proto_rawDescGZIP(), []int{2}
}

func (x *NumericAnnotation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NumericAnnotation) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_storageutil_entity_active_payload_proto protoreflect.FileDescriptor

var file_storageutil_entity_active_payload_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0xe5, 0x01, 0x0a, 0x0e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f,
	0x61, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x47,
	0x0a, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4a, 0x0a, 0x13, 0x6e, 0x75, 0x6d, 0x65, 0x72,
	0x69, 0x63, 0x5f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4e, 0x75,
	0x6d, 0x65, 0x72, 0x69, 0x63, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x12, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x10, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63,
	0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x74, 0x68,
	0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x67, 0x6f, 0x6c, 0x65, 0x6d, 0x2d, 0x62, 0x61, 0x73, 0x65,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storageutil_entity_active_payload_proto_rawDescOnce sync.Once
	file_storageutil_entity_active_payload_proto_rawDescData = file_storageutil_entity_active_payload_proto_rawDesc
)

func file_storageutil_entity_active_payload_proto_rawDescGZIP() []byte {
	file_storageutil_entity_active_payload_proto_rawDescOnce.Do(func() {
		file_storageutil_entity_active_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_storageutil_entity_active_payload_proto_rawDescData)
	})
	return file_storageutil_entity_active_payload_proto_rawDescData
}

var file_storageutil_entity_active_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_storageutil_entity_active_payload_proto_goTypes = []any{
	(*EntityMetaData)(nil),    // 0: entity.EntityMetaData
	(*StringAnnotation)(nil),  // 1: entity.StringAnnotation
	(*NumericAnnotation)(nil), // 2: entity.NumericAnnotation
}
var file_storageutil_entity_active_payload_proto_depIdxs = []int32{
	1, // 0: entity.EntityMetaData.string_annotations:type_name -> entity.StringAnnotation
	2, // 1: entity.EntityMetaData.numeric_annotations:type_name -> entity.NumericAnnotation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storageutil_entity_active_payload_proto_init() }
func file_storageutil_entity_active_payload_proto_init() {
	if File_storageutil_entity_active_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storageutil_entity_active_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storageutil_entity_active_payload_proto_goTypes,
		DependencyIndexes: file_storageutil_entity_active_payload_proto_depIdxs,
		MessageInfos:      file_storageutil_entity_active_payload_proto_msgTypes,
	}.Build()
	File_storageutil_entity_active_payload_proto = out.File
	file_storageutil_entity_active_payload_proto_rawDesc = nil
	file_storageutil_entity_active_payload_proto_goTypes = nil
	file_storageutil_entity_active_payload_proto_depIdxs = nil
}
