name: GoReleaser

on:
  workflow_run:
    workflows: ["nix-build", "self-hosted"]
    types:
      - completed

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' && 
           github.event.workflow_run.name == 'self-hosted' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }} 