name: Nix Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nix-build:
    name: Build with Nix
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: nix build
